
name: Luka workflow
run-name: ${{ github.actor }} fait un ${{ github.event_name }} sur ${{ github.ref }} ğŸš€
on:
  push:
    branches:    
      - luka-branch
jobs:
  luka-workflow:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ Hello world - ${{ github.event_name }}."
      - run: echo "ğŸ‰ Bonjour - ${{ github.event_name }}."
      - run: echo "ğŸ‰ Bonjour - ${{ github.event_name }}."